### ISSUE TITLE
autocorrect ignores spelllang variable

### ISSUE THREAD

**Issue by pl0pix** [sedm0784/vim-you-autocorrect#3]
When I set `spl=de` in a modeline Autocorrect uses `en` spell correction.  Is there a way to configure other languages than en?

**Comment by sedm0784** [comment]
I'm afraid I can't reproduce this. Using the following modeline switches Vim You, Autocorrect! over to German spellings for me:

    " vi:spl=de

Some questions to help me track this down:

1. What happens if you `:DisableAutocorrect` and then try correcting a spelling manually with the normal-mode command `1z=`?
2. What is the output of the command `:verbose set spl?`

**Comment by pl0pix** [comment]
1.
I get the  english correction
2.
spelllang=en

Here is what I do:

```
echo "# vim: set et:sts=4:spelllang=de:spell:" > test.txt
vim test.txt
```

In vim I do `:EnableAutocorrect`
I 
type 'korrrekt' and get an english correction.

```
echo "vim: set et sts=4 tw=80 spl=de spell:" > test.txt
vim test.txt
```

When I type I get german corrections. The modeline was wrong. Sorry, my bad.

**Comment by sedm0784** [comment]
Thanks for letting me know.
